### ISSUE TITLE
[Maybe a bug] "Undefined: NaN"

### ISSUE THREAD

**Issue by tagnullde** [SDoehren/day-night-cycle#1]
Everything is the newest stable version possible.
Not sure if a bug - because it doesn't seem to throw errors. But isn't "NaN" a thing people try to avoid?

![image](https://user-images.githubusercontent.com/44159008/133938968-0e5feeac-ad65-4c36-8577-4966ba23c3e7.png)

**Comment by SDoehren** [comment]
Thank you for raising, that is debuging, it is fine though.
