### ISSUE TITLE
 infinite warning loop in logs

### ISSUE THREAD

**Issue by CaosFR** [SDoehren/day-night-cycle#13]
Hi,

I hope you can quicly solve this "little" problem. Unfortunately I have to deactivate your module which I love otherwise my games become unstable

**Describe the bug**
If we use your module a warning is create in the console after each seconde in the game. Which makes sense, given that every second your module can potentially update the map's darkness. However, the errors generated quickly number in the thousands, causing performance problems and making the console unreadable.

**To Reproduce**
1. Active your module
2. Click on 'unpause'
3. Open the 'console

**Expected behavior**
Stop the warning loop in the console

**Screenshots**
After 10s of activation
![image](https://github.com/user-attachments/assets/3188053d-16a8-4660-a6ea-c4d60f9b6c9c) 

**Foundry :**
 - Foundry Version 12.331
 - System 3.3.1
 - Module Version 0008

**Desktop :**
 - OS: W10 up to date
 - Browser Chromium
 - Version  126.0.6478.114

**Additional context**
Thanks for your module I use it since the first release :)

**Comment by SDoehren** [comment]
Fix release - V0009

**Comment by CaosFR** [comment]
Thanks :)
