### ISSUE TITLE
SceneData darkness "NaN" is not a number between 0 and 1

### ISSUE THREAD

**Issue by gsterling** [SDoehren/day-night-cycle#2]
**Describe the bug**
When using the default settings with simple calendar. The darkness is not changed. Instead there is a new error shown every second. See the screenshots.

**To Reproduce**
1. Activate Module
2. Unpause game

**Expected behavior**
Change darkness according to time.

**Screenshots**
![image](https://user-images.githubusercontent.com/58980630/148769287-c2f68c6e-62a5-49d5-9878-c6c6b54218a7.png)
![image](https://user-images.githubusercontent.com/58980630/148769435-e00621dd-273d-4465-89e9-7258ad63aa04.png)

**Foundry (please complete the following information):**
 - Foundry Version: latest (9.242)
 - System: Splittermond latest (0.7.3)
 - Module Version: latest (0004)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chromium 96.0.4664.110

**Additional context**
* German and english translations affected
* Changing darkness by hand to "reset" it, did nothing.
* Do you need anything else from me?

**Comment by SDoehren** [comment]
Turn on Debug then hit F12 and get the output from the console please?  

Also, can you right click the scene and see what the darkness level is set to?  
Then change it to 0.5 manually and try running again.

**Comment by gsterling** [comment]
> Turn on Debug then hit F12 and get the output from the console please?

![image](https://user-images.githubusercontent.com/58980630/148774951-6adcd7bf-36e0-4ebc-aa7a-41bed9f5e3fc.png)

> Also, can you right click the scene and see what the darkness level is set to? 

It was 0 before.

> Then change it to 0.5 manually and try running again.

![image](https://user-images.githubusercontent.com/58980630/148775156-6596d018-3bb1-40a7-bdd6-4d50b1498351.png)
![image](https://user-images.githubusercontent.com/58980630/148775043-4ac347c2-71ec-4be5-b317-c609daed08a4.png)

It does not change anything.

**Comment by CaosFR** [comment]
Same problem for me darkness is not update and I have this error in loop when Day and Night Cicle is on. Custom setting get the same error.

**Comment by SDoehren** [comment]
what system are you using?  
I'm failing to replicate on my end, I'm wondering if it is system related.

**Comment by CaosFR** [comment]
Thanks for your help :

Hope it's will help :
Foundry Version: latest (9.242)
System: Dnd5e latest (1.5.7)
Module Version: latest (0004)

OS: Debian 11
Browser: Chromium 97.0.4692.71

Additional context
French and english translations affected.
Reinstall this module dont work.
With all other not needed module disable, the problem persist.
Problem appear after update to v9.

**Comment by gsterling** [comment]
> I'm failing to replicate on my end, I'm wondering if it is system related.

I also tested it with [SWADE](https://foundryvtt.com/packages/swade/) now and it gives me the same error. Only three modules are enabled:
* Day Night Cycle
* libWrapper
* Simple Calendar

**Comment by SDoehren** [comment]
Got it.

It's an interaction of the Moon Cycles and Language.

**Comment by CaosFR** [comment]
Nice :), thanks for your work.

**Comment by SDoehren** [comment]
Released - Moon Effects are unavailable in non English Languages, but core settings are working again.

**Comment by CaosFR** [comment]
it's working, thanks.
