### ISSUE TITLE
Install renders scenes unable to be saved.

### ISSUE THREAD

**Issue by mundusartis** [SDoehren/day-night-cycle#4]
**Describe the bug**
Upon installing day night cycle, the 'Configure Scene' screen in Foundry stops saving changes. 

**To Reproduce**
1. Confirm you are able to save changes made on any 'Configure Scene' screen
2. Go to 'Configure Modules'
3. Click on checkbox for 'Day Night Cycle'
4. Save changes
5. Wait for scene to reload
6. Open 'Configure Scene' screen on any Scene.
7. Make any change and attempt to click 'Save Changes'

**Expected behavior**
In normal conditions, either an error will come up if a parameter is incorrect, or the window will close.

**Foundry (please complete the following information):**
 - Foundry Version 9 build no. 269
 - System DnD5e
 - Module Version 0005

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version [e.g. 22] 102.0.5005.115

**Additional context**
See below for currently active modules

![image](https://user-images.githubusercontent.com/107834422/174540442-1ef2522e-53cd-4618-a462-860e0ee360d3.png)
![image](https://user-images.githubusercontent.com/107834422/174540531-994473e4-f406-40f1-8baa-8a0e0844eed1.png)
![image](https://user-images.githubusercontent.com/107834422/174540604-99e7888a-a8ad-46cb-bf14-0f9d5be6b501.png)
![image](https://user-images.githubusercontent.com/107834422/174540721-e0091472-f767-4388-acd4-6fe1c9e0c72e.png)
![image](https://user-images.githubusercontent.com/107834422/174540766-9d18ef9f-3cd4-4389-80f1-5a0ac52a5d01.png)

**Comment by SDoehren** [comment]
Hi

Please try loading the console under F12 and repeating the process.  I would expect an error to appear in there.

There are a lot of potential clashes in that module list.

**Comment by mundusartis** [comment]
"An invalid form control with name='DNC.MaxLight' is not focusable." comes
up in the console errors when trying to execute the operation (with day
night cycle enabled). With day night cycle disabled, said error does not
appear.

**Comment by SDoehren** [comment]
Something is interfering with the form handling, it really could be anything and I'm not seeing the issue at my end.

The only thing I can suggest is trying combinations of modules to see which the error triggers with and without

**Comment by SDoehren** [comment]
No further reports of this issue and unable to replicate.
