### ISSUE TITLE
Day/Night cycle only working on active Scene

### ISSUE THREAD

**Issue by Gensokian** [SDoehren/day-night-cycle#6]
**Describe the bug**
When changing the time in the calendar, the day/night cycle only changes for the currently active scene, but not for any other scene, players are in.

**To Reproduce**
1. Open a scene
2. Click on 'activate'
3. Change day time
4. Note, that the Darkness-Level changes
5. go to other scene
6. change time
7. Scene doesn't darken, until activated and changed time

**Expected behavior**
Time works on a global basis: So when the party splits, and 2 Maps are considered active, both maps should update.

**Screenshots**
[Video](https://user-images.githubusercontent.com/9213561/183612644-ed5493c3-63f0-4dff-a74b-4ee128fe3b7f.mp4)

**Foundry:**
 - Foundry Version: 9 build 269
 - System DND5E
 - Module Version: 0005

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Vivaldi/Chrome/Edge
 - Version Latest

**Comment by SDoehren** [comment]
This one have been on my back log for awhile.

A balancing processing vs use.  No point updating maps not being used.  

Probably update all on the Nav.

**Comment by Gensokian** [comment]
One thing that might work is to get every map with active players in it?
Or activate the day/night cycle on scene load whenever a player jumps to that map?

Most GMs I know don't use the "display on nav" too often. They basically go "Welp, it's there allright!" and clutter it up quite excessively.

I never had any instance with more than 3 Maps loaded at the time; Party split + GM doing GM things on other maps.

**Comment by SDoehren** [comment]
Implemented in the next version.  Will update the lighting on active scene and any scene being viewed.

**Comment by SDoehren** [comment]
Implemented
