### ISSUE TITLE
Update to v10

### ISSUE THREAD

**Issue by CaosFR** [SDoehren/day-night-cycle#7]
Hi,

Thanks for your module and work. Does it possible to update the module for the v10 ?

In the module.json I can see :

```
  "minimumCoreVersion": "9",
  "compatibleCoreVersion": "9",
```

Happy dev

**Comment by SDoehren** [comment]
Early testing suggests DNC works in V10, it's just not officially supported as yet.

**Comment by SDoehren** [comment]
Leaving open for others to see

**Comment by SDoehren** [comment]
Implemented

**Comment by CaosFR** [comment]
Thanks ! :)
